"""Language mapping module for acapela-group."""

LANGUAGES = {
    'ARABIC': 'sonid0',
    'CATALAN': 'sonid1',
    'CZECH': 'sonid2',
    'DANISH': 'sonid3',
    'DUTCH (BELGIUM)': 'sonid4',
    'DUTCH (NETHERLANDS)': 'sonid5',
    'ENGLISH (AU)': 'sonid6',
    'ENGLISH (INDIA)': 'sonid7',
    'ENGLISH (SCOTTISH)': 'sonid8',
    'ENGLISH (UK)': 'sonid9',
    'ENGLISH (USA)': 'sonid10',
    'FAROESE': 'sonid11',
    'FINNISH': 'sonid12',
    'FRENCH (BELGIUM)': 'sonid13',
    'FRENCH (CANADA)': 'sonid14',
    'FRENCH (FRANCE)': 'sonid15',
    'GERMAN': 'sonid16',
    'GREEK': 'sonid17',
    'ITALIAN': 'sonid18',
    'JAPANESE': 'sonid19',
    'KOREAN': 'sonid20',
    'MANDARIN': 'sonid21',
    'NORWEGIAN': 'sonid22',
    'POLISH': 'sonid23',
    'PORTUGUESE (BRAZIL)': 'sonid24',
    'PORTUGUESE (PORTUGAL)': 'sonid25',
    'RUSSIAN': 'sonid26',
    'SAMI (NORTH)': 'sonid27',
    'SPANISH (SPAIN)': 'sonid28',
    'SPANISH (US)': 'sonid29',
    'SWEDISH': 'sonid30',
    'SWEDISH (FINLAND)': 'sonid31',
    'SWEDISH (GOTHENBURG)': 'sonid32',
    'SWEDISH (SCANIAN)': 'sonid33',
    'TURKISH': 'sonid34'
}
